fx_version 'cerulean'
game 'gta5'
version '0.0.1'
author 'Natural'
export 'Notification'
description 'UIBASSIC | Player'
client_script 'client/*.lua'
ui_page 'html/ui.html'
file 'html/***/***/***/***'